name: API CI

on:
  push:
    branches:
      - main 
      - feature/*
  pull_request:
    branches: [ main ]
      
jobs:
  Lint-and-Test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2


    - name: Run unit tests
      run: | 
        cd app/api/ 
        python3 --version 
        sudo apt install -y python3-pip 
        sudo pip3 install -r requirements.txt
        export API_KEY=${{ secrets.API_KEY }}
        python3 -m unittest tests/api_test.py 
    
    - name: lint
      run: |
        sudo pip3 install -y pylint
        pylint --fail-under=9 src/main.py  
  
  Docker-build-and-push:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push the Docker image
        run: |
          cd app/api/ 
          docker build . --file dockerfile --tag loganbobo97/weather-app:latest
          docker push loganbobo97/weather-app:latest



