name: API CI

on:
  push:
    branches:
      - main 
      - feature/*
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Run unit tests
      run: | 
        cd app/api/ 
        python3 --version 
        sudo apt install -y python3-pip 
        sudo pip3 install -r requirements.txt pytest 
        pytest --version 
        export PYTHONPATH=. 
        pytest -vqrA tests/api_test.py
      
    - name: Build the Docker image
      run: |
        cd app/api/ 
        version=$(date +%s)
        docker build . --file dockerfile --tag loganbobo97/weather-app:$version
        docker images
        
    - name: Push docker image
      run : |
        cd app/api/
        docker login --username loganbobo97 --password-stdin < ${{ secrets.DOCKER_TOKEN }}
        docker push loganbobo97/weather-app:$version
    
        
    

      
