name: API CI

on:
  push:
    branches:
      - main 
      - feature/*
  pull_request:
    branches: [ main ]
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2


    - name: Run unit tests
      run: | 
        cd app/api/ 
        python3 --version 
        sudo apt install -y python3-pip 
        sudo pip3 install -r requirements.txt pytest 
        pytest --version 
        export PYTHONPATH=. 
        pytest -vqrA tests/api_test.py
        
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build and push the Docker image
      run: |
        export VERSION=$(date +%s)
        cd app/api/ 
        docker build . --file dockerfile --tag loganbobo97/weather-app:$VERSION
        docker push loganbobo97/weather-app:$VERSION



